Add the ability to send notification through Pushover
rickstaa/tmux-notify pull request #57
Opened 2024-04-07 05:44 UTC by lunfel

The title says it all! I have used almost the same code pattern than the one for Telegram. The proper documentation has also been written

2025-01-08 16:48 UTC, rickstaa commented on scripts/helpers.sh
> +pushover_available() {
@lunfel can we add a docstring.

2025-01-08 16:49 UTC, rickstaa commented on README.md
> +
@lunfel please remove extra line.

2025-01-08 16:50 UTC, rickstaa commented on README.md
>  Additionally, you can use the `set -g @tnotify-telegram-all 'on'` option to send all notifications to telegram.
To ensure correct formatting please keep the extra line between the text and the admonition.

2025-01-08 16:51 UTC, rickstaa requested changes
@lunfel, great addition! I made some minor comments, but apart from that, it is good for a merge 🚀.

2025-01-11 15:46 UTC, lunfel commented on scripts/helpers.sh
> +pushover_available() {
Let me know if there is a specific format for the docstring. I just added a small description for now.

2025-01-11 15:50 UTC, lunfel commented
@rickstaa I have applied the requested changes. Let me know if there is anything else you wish me to change in this PR.

2025-01-26 09:26 UTC, rickstaa approved these changes
LGTM, thanks for your contribution!

2025-01-26 09:27 UTC, merged